#!/bin/bash
set -u

osname="$(uname --operating-system)"
if [[ "$osname" == *"Linux" ]]; then
   JenkinsJobs/Linux/FileArb-Debug-Clang.sh
elif [ "$osname" == "Msys" ]; then
	powershell.exe JenkinsJobs/Windows/FileArb-PyUtils.ps1
   powershell.exe JenkinsJobs/Windows/FileArb-Debug.ps1
fi
jenkinsJobExitCode=$?
if [ "$jenkinsJobExitCode" -ne 0 ]; then
   echo "======================================================================================"
   echo "pre-commit: Jenkins job failed with exit code $jenkinsJobExitCode. Disallowing commit."
   echo "======================================================================================"
   exit 1
fi
echo "==================================================="
echo "pre-commit: Jenkins job succeeded. Allowing commit."
echo "==================================================="
