#!/bin/bash
set -eu

osname="$(uname --operating-system)"
if [[ "$osname" == *"Linux" ]]; then
   ./JenkinsJobs/Linux/FileArb-Cppcheck.sh
   ./JenkinsJobs/Linux/FileArbPyUtils-Mypy-Flake8-Pylint-SonarQube.sh
   ./JenkinsJobs/Linux/FileArb-Debug-Clang.sh
elif [ "$osname" == "Msys" ]; then
   powershell.exe JenkinsJobs/Windows/FileArb-Cppcheck.ps1
   powershell.exe JenkinsJobs/Windows/FileArbPyUtils-Mypy-Flake8-Pylint-SonarQube.ps1
   powershell.exe JenkinsJobs/Windows/FileArb-Debug.ps1
fi
jenkinsJobExitCode=$?
if [ "$jenkinsJobExitCode" -ne 0 ]; then
   echo "======================================================================================"
   echo "pre-commit: Jenkins job failed with exit code $jenkinsJobExitCode. Disallowing commit."
   echo "======================================================================================"
   exit 1
fi
echo "==================================================="
echo "pre-commit: Jenkins job succeeded. Allowing commit."
echo "==================================================="
